version: '3'
services:
  spring-boot-app:
      build:
        context: ./evictionEduspring
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: dbc:h2:file:./TestDataBase
        SPRING_DATASOURCE_USERNAME: sa
        SPRING_DATASOURCE_PASSWORD: ghj

  react-app:
      build:
        context: ./eviction2app
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
